// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file enum.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file enum.proto.
 */
export const file_enum = /*@__PURE__*/
  fileDesc("CgplbnVtLnByb3RvEghQcm90b2NvbCo1CgpPYmplY3RUeXBlEgoKBlBMQVlFUhAAEgsKB01PTlNURVIQARIOCgpQUk9KRUNUSUxFEAJiBnByb3RvMw");

/**
 * Describes the enum Protocol.ObjectType.
 */
export const ObjectTypeSchema = /*@__PURE__*/
  enumDesc(file_enum, 0);

/**
 * @generated from enum Protocol.ObjectType
 */
export const ObjectType = /*@__PURE__*/
  tsEnum(ObjectTypeSchema);

