// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file game.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_client } from "./client_pb";
import { file_server } from "./server_pb";
import { file_struct } from "./struct_pb";
import { file_enum } from "./enum_pb";

/**
 * Describes the file game.proto.
 */
export const file_game = /*@__PURE__*/
  fileDesc("CgpnYW1lLnByb3RvEghQcm90b2NvbCJfChFDMkJfSW5pdGlhbFBhY2tldBIoCgpQbGF5ZXJJbmZvGAEgASgLMhQuUHJvdG9jb2wuT2JqZWN0SW5mbxIOCgZyb29tSWQYAiABKA0SEAoIbmlja25hbWUYAyABKAkiNQoNQjJDX0VudGVyUm9vbRIkCgRtZXRhGAEgASgLMhYuUHJvdG9jb2wuUzJDX01ldGFkYXRhIkcKDUIyQ19HYW1lU3RhcnQSDwoHaXNTdGFydBgBIAEoCBIlCgdwbGF5ZXJzGAIgAygLMhQuUHJvdG9jb2wuT2JqZWN0SW5mbyJuCghDMkJfTW92ZRIoCgpvYmplY3RJbmZvGAEgASgLMhQuUHJvdG9jb2wuT2JqZWN0SW5mbxIoCgpvYmplY3RUeXBlGAIgASgOMhQuUHJvdG9jb2wuT2JqZWN0VHlwZRIOCgZyb29tSWQYAyABKA0iXgoIQjJDX01vdmUSKAoKb2JqZWN0SW5mbxgBIAEoCzIULlByb3RvY29sLk9iamVjdEluZm8SKAoKb2JqZWN0VHlwZRgCIAEoDjIULlByb3RvY29sLk9iamVjdFR5cGViBnByb3RvMw", [file_client, file_server, file_struct, file_enum]);

/**
 * Describes the message Protocol.C2B_InitialPacket.
 * Use `create(C2B_InitialPacketSchema)` to create a new message.
 */
export const C2B_InitialPacketSchema = /*@__PURE__*/
  messageDesc(file_game, 0);

/**
 * Describes the message Protocol.B2C_EnterRoom.
 * Use `create(B2C_EnterRoomSchema)` to create a new message.
 */
export const B2C_EnterRoomSchema = /*@__PURE__*/
  messageDesc(file_game, 1);

/**
 * Describes the message Protocol.B2C_GameStart.
 * Use `create(B2C_GameStartSchema)` to create a new message.
 */
export const B2C_GameStartSchema = /*@__PURE__*/
  messageDesc(file_game, 2);

/**
 * Describes the message Protocol.C2B_Move.
 * Use `create(C2B_MoveSchema)` to create a new message.
 */
export const C2B_MoveSchema = /*@__PURE__*/
  messageDesc(file_game, 3);

/**
 * Describes the message Protocol.B2C_Move.
 * Use `create(B2C_MoveSchema)` to create a new message.
 */
export const B2C_MoveSchema = /*@__PURE__*/
  messageDesc(file_game, 4);

