// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file init.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file init.proto.
 */
export const file_init = /*@__PURE__*/
  fileDesc("Cgppbml0LnByb3RvEghQcm90b2NvbCIaCghMMkNfSW5pdBIOCgZ1c2VySWQYASABKAUiWAoRQzJMX0luaXRpYWxQYWNrZXQSDgoGdXNlcklkGAEgASgFEhAKCHBsYXllcklkGAIgASgFEg8KB2xhdGVuY3kYAyABKAISEAoIbmlja25hbWUYBCABKAkiJQoRQjJMX0luaXRpYWxQYWNrZXQSEAoIc2VydmVySWQYASABKAliBnByb3RvMw");

/**
 * Describes the message Protocol.L2C_Init.
 * Use `create(L2C_InitSchema)` to create a new message.
 */
export const L2C_InitSchema = /*@__PURE__*/
  messageDesc(file_init, 0);

/**
 * Describes the message Protocol.C2L_InitialPacket.
 * Use `create(C2L_InitialPacketSchema)` to create a new message.
 */
export const C2L_InitialPacketSchema = /*@__PURE__*/
  messageDesc(file_init, 1);

/**
 * Describes the message Protocol.B2L_InitialPacket.
 * Use `create(B2L_InitialPacketSchema)` to create a new message.
 */
export const B2L_InitialPacketSchema = /*@__PURE__*/
  messageDesc(file_init, 2);

