// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file room.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_struct } from "./struct_pb";

/**
 * Describes the file room.proto.
 */
export const file_room = /*@__PURE__*/
  fileDesc("Cgpyb29tLnByb3RvEghQcm90b2NvbCI5ChVDMkxfQ3JlYXRlUm9vbVJlcXVlc3QSDAoEbmFtZRgBIAEoCRISCgptYXhVc2VyTnVtGAIgASgFIk0KFkwyQ19DcmVhdGVSb29tUmVzcG9uc2USEQoJaXNTdWNjZXNzGAEgASgIEiAKBHJvb20YAiABKAsyEi5Qcm90b2NvbC5Sb29tRGF0YSI/ChlMMkJfQ3JlYXRlR2FtZVJvb21SZXF1ZXN0Eg4KBnJvb21JZBgBIAEoBRISCgptYXhQbGF5ZXJzGAIgASgFIj4KGUIyTF9DcmVhdGVHYW1lUm9vbVJlc3BvbmUSEQoJaXNDcmVhdGVkGAEgASgIEg4KBnJvb21JZBgCIAEoBSI4ChRMMkJfR2FtZVN0YXJ0UmVxdWVzdBIMCgRuYW1lGAEgASgJEhIKCm1heFVzZXJOdW0YAiABKAUiGAoWQzJMX0dldFJvb21MaXN0UmVxdWVzdCI8ChdMMkNfR2V0Um9vbUxpc3RSZXNwb25zZRIhCgVyb29tcxgBIAMoCzISLlByb3RvY29sLlJvb21EYXRhIiUKE0MyTF9Kb2luUm9vbVJlcXVlc3QSDgoGcm9vbUlkGAEgASgFIksKFEwyQ19Kb2luUm9vbVJlc3BvbnNlEhEKCWlzU3VjY2VzcxgBIAEoCBIgCgRyb29tGAIgASgLMhIuUHJvdG9jb2wuUm9vbURhdGEiFgoUQzJMX0xlYXZlUm9vbVJlcXVlc3QiKgoVTDJDX0xlYXZlUm9vbVJlc3BvbnNlEhEKCWlzU3VjY2VzcxgBIAEoCCIrChlMMkNfTGVhdmVSb29tTm90aWZpY2F0aW9uEg4KBnVzZXJJZBgBIAEoBSJAChhMMkNfSm9pblJvb21Ob3RpZmljYXRpb24SJAoIam9pblVzZXIYASABKAsyEi5Qcm90b2NvbC5Vc2VyRGF0YSIvCg1DMkxfR2FtZVN0YXJ0Eg4KBnVzZXJJZBgBIAEoBRIOCgZyb29tSWQYAiABKA0iNQoOTDJDX1BsYXllckxpc3QSIwoHcGxheWVycxgBIAMoCzISLlByb3RvY29sLlVzZXJEYXRhIk0KDUwyQ19HYW1lU3RhcnQSEgoKZ2FtZVJvb21JcBgBIAEoCRIUCgxnYW1lUm9vbVBvcnQYAiABKAkSEgoKZ2FtZVJvb21JZBgDIAEoBWIGcHJvdG8z", [file_struct]);

/**
 * Describes the message Protocol.C2L_CreateRoomRequest.
 * Use `create(C2L_CreateRoomRequestSchema)` to create a new message.
 */
export const C2L_CreateRoomRequestSchema = /*@__PURE__*/
  messageDesc(file_room, 0);

/**
 * Describes the message Protocol.L2C_CreateRoomResponse.
 * Use `create(L2C_CreateRoomResponseSchema)` to create a new message.
 */
export const L2C_CreateRoomResponseSchema = /*@__PURE__*/
  messageDesc(file_room, 1);

/**
 * Describes the message Protocol.L2B_CreateGameRoomRequest.
 * Use `create(L2B_CreateGameRoomRequestSchema)` to create a new message.
 */
export const L2B_CreateGameRoomRequestSchema = /*@__PURE__*/
  messageDesc(file_room, 2);

/**
 * Describes the message Protocol.B2L_CreateGameRoomRespone.
 * Use `create(B2L_CreateGameRoomResponeSchema)` to create a new message.
 */
export const B2L_CreateGameRoomResponeSchema = /*@__PURE__*/
  messageDesc(file_room, 3);

/**
 * Describes the message Protocol.L2B_GameStartRequest.
 * Use `create(L2B_GameStartRequestSchema)` to create a new message.
 */
export const L2B_GameStartRequestSchema = /*@__PURE__*/
  messageDesc(file_room, 4);

/**
 * Describes the message Protocol.C2L_GetRoomListRequest.
 * Use `create(C2L_GetRoomListRequestSchema)` to create a new message.
 */
export const C2L_GetRoomListRequestSchema = /*@__PURE__*/
  messageDesc(file_room, 5);

/**
 * Describes the message Protocol.L2C_GetRoomListResponse.
 * Use `create(L2C_GetRoomListResponseSchema)` to create a new message.
 */
export const L2C_GetRoomListResponseSchema = /*@__PURE__*/
  messageDesc(file_room, 6);

/**
 * Describes the message Protocol.C2L_JoinRoomRequest.
 * Use `create(C2L_JoinRoomRequestSchema)` to create a new message.
 */
export const C2L_JoinRoomRequestSchema = /*@__PURE__*/
  messageDesc(file_room, 7);

/**
 * Describes the message Protocol.L2C_JoinRoomResponse.
 * Use `create(L2C_JoinRoomResponseSchema)` to create a new message.
 */
export const L2C_JoinRoomResponseSchema = /*@__PURE__*/
  messageDesc(file_room, 8);

/**
 * Describes the message Protocol.C2L_LeaveRoomRequest.
 * Use `create(C2L_LeaveRoomRequestSchema)` to create a new message.
 */
export const C2L_LeaveRoomRequestSchema = /*@__PURE__*/
  messageDesc(file_room, 9);

/**
 * Describes the message Protocol.L2C_LeaveRoomResponse.
 * Use `create(L2C_LeaveRoomResponseSchema)` to create a new message.
 */
export const L2C_LeaveRoomResponseSchema = /*@__PURE__*/
  messageDesc(file_room, 10);

/**
 * Describes the message Protocol.L2C_LeaveRoomNotification.
 * Use `create(L2C_LeaveRoomNotificationSchema)` to create a new message.
 */
export const L2C_LeaveRoomNotificationSchema = /*@__PURE__*/
  messageDesc(file_room, 11);

/**
 * Describes the message Protocol.L2C_JoinRoomNotification.
 * Use `create(L2C_JoinRoomNotificationSchema)` to create a new message.
 */
export const L2C_JoinRoomNotificationSchema = /*@__PURE__*/
  messageDesc(file_room, 12);

/**
 * Describes the message Protocol.C2L_GameStart.
 * Use `create(C2L_GameStartSchema)` to create a new message.
 */
export const C2L_GameStartSchema = /*@__PURE__*/
  messageDesc(file_room, 13);

/**
 * Describes the message Protocol.L2C_PlayerList.
 * Use `create(L2C_PlayerListSchema)` to create a new message.
 */
export const L2C_PlayerListSchema = /*@__PURE__*/
  messageDesc(file_room, 14);

/**
 * Describes the message Protocol.L2C_GameStart.
 * Use `create(L2C_GameStartSchema)` to create a new message.
 */
export const L2C_GameStartSchema = /*@__PURE__*/
  messageDesc(file_room, 15);

