// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file server.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file server.proto.
 */
export const file_server = /*@__PURE__*/
  fileDesc("CgxzZXJ2ZXIucHJvdG8SCFByb3RvY29sIjcKDFMyQ19NZXRhZGF0YRIUCgxyZXNwb25zZUNvZGUYASABKA0SEQoJdGltZXN0YW1wGAIgASgDIkAKCEwyQ19Jbml0EiQKBG1ldGEYASABKAsyFi5Qcm90b2NvbC5TMkNfTWV0YWRhdGESDgoGdXNlcklkGAIgASgJIkIKCVMyQ19FcnJvchIkCgRtZXRhGAEgASgLMhYuUHJvdG9jb2wuUzJDX01ldGFkYXRhEg8KB21lc3NhZ2UYAiABKAkiJQoRQjJMX0luaXRpYWxQYWNrZXQSEAoIc2VydmVySWQYASABKAliBnByb3RvMw");

/**
 * Describes the message Protocol.S2C_Metadata.
 * Use `create(S2C_MetadataSchema)` to create a new message.
 */
export const S2C_MetadataSchema = /*@__PURE__*/
  messageDesc(file_server, 0);

/**
 * Describes the message Protocol.L2C_Init.
 * Use `create(L2C_InitSchema)` to create a new message.
 */
export const L2C_InitSchema = /*@__PURE__*/
  messageDesc(file_server, 1);

/**
 * Describes the message Protocol.S2C_Error.
 * Use `create(S2C_ErrorSchema)` to create a new message.
 */
export const S2C_ErrorSchema = /*@__PURE__*/
  messageDesc(file_server, 2);

/**
 * Describes the message Protocol.B2L_InitialPacket.
 * Use `create(B2L_InitialPacketSchema)` to create a new message.
 */
export const B2L_InitialPacketSchema = /*@__PURE__*/
  messageDesc(file_server, 3);

