// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file struct.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_enum } from "./enum_pb";

/**
 * Describes the file struct.proto.
 */
export const file_struct = /*@__PURE__*/
  fileDesc("CgxzdHJ1Y3QucHJvdG8SCFByb3RvY29sIjEKB1Bvc0luZm8SEAoIb2JqZWN0SWQYASABKAkSCQoBeBgCIAEoAhIJCgF5GAMgASgCIiwKCFVzZXJJbmZvEg4KBnVzZXJJZBgBIAEoCRIQCghuaWNrbmFtZRgCIAEoCSJYCghSb29tSW5mbxIOCgZyb29tSWQYASABKA0SEAoIcm9vbU5hbWUYAiABKAkSFgoOY3VycmVudFBsYXllcnMYAyABKA0SEgoKbWF4UGxheWVycxgEIAEoDSJFCgpPYmplY3RJbmZvEiIKB3Bvc2luZm8YASABKAsyES5Qcm90b2NvbC5Qb3NJbmZvEhMKC3ByZWZhYkluZGV4GAIgASgNYgZwcm90bzM", [file_enum]);

/**
 * Describes the message Protocol.PosInfo.
 * Use `create(PosInfoSchema)` to create a new message.
 */
export const PosInfoSchema = /*@__PURE__*/
  messageDesc(file_struct, 0);

/**
 * Describes the message Protocol.UserInfo.
 * Use `create(UserInfoSchema)` to create a new message.
 */
export const UserInfoSchema = /*@__PURE__*/
  messageDesc(file_struct, 1);

/**
 * Describes the message Protocol.RoomInfo.
 * Use `create(RoomInfoSchema)` to create a new message.
 */
export const RoomInfoSchema = /*@__PURE__*/
  messageDesc(file_struct, 2);

/**
 * Describes the message Protocol.ObjectInfo.
 * Use `create(ObjectInfoSchema)` to create a new message.
 */
export const ObjectInfoSchema = /*@__PURE__*/
  messageDesc(file_struct, 3);

