// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file character.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_struct } from "./struct_pb";
import { file_enum } from "./enum_pb";

/**
 * Describes the file character.proto.
 */
export const file_character = /*@__PURE__*/
  fileDesc("Cg9jaGFyYWN0ZXIucHJvdG8SCFByb3RvY29sIjEKGUMyQl9Qb3NpdGlvblVwZGF0ZVJlcXVlc3QSCQoBeBgBIAEoARIJCgF5GAIgASgBIlUKHkIyQ19Qb3NpdGlvblVwZGF0ZU5vdGlmaWNhdGlvbhIzChJjaGFyYWN0ZXJQb3NpdGlvbnMYASADKAsyFy5Qcm90b2NvbC5DaGFyYWN0ZXJEYXRhIjoKEkMyQl9Vc2VDYXJkUmVxdWVzdBIkCghjYXJkVHlwZRgBIAEoDjISLlByb3RvY29sLkNhcmRUeXBlIiwKF0IyQ19Vc2VDYXJkTm90aWZpY2F0aW9uEhEKCWlzU3VjY2VzcxgBIAEoCGIGcHJvdG8z", [file_struct, file_enum]);

/**
 * Describes the message Protocol.C2B_PositionUpdateRequest.
 * Use `create(C2B_PositionUpdateRequestSchema)` to create a new message.
 */
export const C2B_PositionUpdateRequestSchema = /*@__PURE__*/
  messageDesc(file_character, 0);

/**
 * Describes the message Protocol.B2C_PositionUpdateNotification.
 * Use `create(B2C_PositionUpdateNotificationSchema)` to create a new message.
 */
export const B2C_PositionUpdateNotificationSchema = /*@__PURE__*/
  messageDesc(file_character, 1);

/**
 * Describes the message Protocol.C2B_UseCardRequest.
 * Use `create(C2B_UseCardRequestSchema)` to create a new message.
 */
export const C2B_UseCardRequestSchema = /*@__PURE__*/
  messageDesc(file_character, 2);

/**
 * Describes the message Protocol.B2C_UseCardNotification.
 * Use `create(B2C_UseCardNotificationSchema)` to create a new message.
 */
export const B2C_UseCardNotificationSchema = /*@__PURE__*/
  messageDesc(file_character, 3);

