// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file client.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file client.proto.
 */
export const file_client = /*@__PURE__*/
  fileDesc("CgxjbGllbnQucHJvdG8SCFByb3RvY29sIjUKDEMyU19NZXRhZGF0YRIOCgZ1c2VySWQYASABKAkSFQoNY2xpZW50VmVyc2lvbhgCIAEoCSJuChFDMkxfSW5pdGlhbFBhY2tldBIkCgRtZXRhGAEgASgLMhYuUHJvdG9jb2wuQzJTX01ldGFkYXRhEhAKCHBsYXllcklkGAIgASgNEg8KB2xhdGVuY3kYAyABKAISEAoIbmlja25hbWUYBCABKAliBnByb3RvMw");

/**
 * Describes the message Protocol.C2S_Metadata.
 * Use `create(C2S_MetadataSchema)` to create a new message.
 */
export const C2S_MetadataSchema = /*@__PURE__*/
  messageDesc(file_client, 0);

/**
 * Describes the message Protocol.C2L_InitialPacket.
 * Use `create(C2L_InitialPacketSchema)` to create a new message.
 */
export const C2L_InitialPacketSchema = /*@__PURE__*/
  messageDesc(file_client, 1);

