// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file monster.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file monster.proto.
 */
export const file_monster = /*@__PURE__*/
  fileDesc("Cg1tb25zdGVyLnByb3RvEghQcm90b2NvbCIZChdDMkJfU3Bhd25Nb25zdGVyUmVxdWVzdCJEChhCMkNfU3Bhd25Nb25zdGVyUmVzcG9uc2USEQoJbW9uc3RlcklkGAEgASgFEhUKDW1vbnN0ZXJOdW1iZXIYAiABKAUiSAocUzJCX1NwYXduTW9uc3Rlck5vdGlmaWNhdGlvbhIRCgltb25zdGVySWQYASABKAUSFQoNbW9uc3Rlck51bWJlchgCIAEoBSJDCh1CMlNfTW9uc3RlckF0dGFja1Rvd2VyUmVxdWVzdBIRCgltb25zdGVySWQYASABKAUSDwoHdG93ZXJJZBgCIAEoBSJICh1TMkJfVXBkYXRlVG93ZXJIUE5vdGlmaWNhdGlvbhIPCgd0b3dlcklkGAEgASgFEhYKDnVwZGF0ZWRUb3dlckhQGAIgASgFIi4KHEIyU19Nb25zdGVyQXR0YWNrQmFzZVJlcXVlc3QSDgoGZGFtYWdlGAEgASgFIiwKF0MyQl9Nb25zdGVyRGVhdGhSZXF1ZXN0EhEKCW1vbnN0ZXJJZBgBIAEoBSIxChxCMkNfTW9uc3RlckRlYXRoTm90aWZpY2F0aW9uEhEKCW1vbnN0ZXJJZBgBIAEoBWIGcHJvdG8z");

/**
 * Describes the message Protocol.C2B_SpawnMonsterRequest.
 * Use `create(C2B_SpawnMonsterRequestSchema)` to create a new message.
 */
export const C2B_SpawnMonsterRequestSchema = /*@__PURE__*/
  messageDesc(file_monster, 0);

/**
 * Describes the message Protocol.B2C_SpawnMonsterResponse.
 * Use `create(B2C_SpawnMonsterResponseSchema)` to create a new message.
 */
export const B2C_SpawnMonsterResponseSchema = /*@__PURE__*/
  messageDesc(file_monster, 1);

/**
 * Describes the message Protocol.S2B_SpawnMonsterNotification.
 * Use `create(S2B_SpawnMonsterNotificationSchema)` to create a new message.
 */
export const S2B_SpawnMonsterNotificationSchema = /*@__PURE__*/
  messageDesc(file_monster, 2);

/**
 * Describes the message Protocol.B2S_MonsterAttackTowerRequest.
 * Use `create(B2S_MonsterAttackTowerRequestSchema)` to create a new message.
 */
export const B2S_MonsterAttackTowerRequestSchema = /*@__PURE__*/
  messageDesc(file_monster, 3);

/**
 * Describes the message Protocol.S2B_UpdateTowerHPNotification.
 * Use `create(S2B_UpdateTowerHPNotificationSchema)` to create a new message.
 */
export const S2B_UpdateTowerHPNotificationSchema = /*@__PURE__*/
  messageDesc(file_monster, 4);

/**
 * Describes the message Protocol.B2S_MonsterAttackBaseRequest.
 * Use `create(B2S_MonsterAttackBaseRequestSchema)` to create a new message.
 */
export const B2S_MonsterAttackBaseRequestSchema = /*@__PURE__*/
  messageDesc(file_monster, 5);

/**
 * Describes the message Protocol.C2B_MonsterDeathRequest.
 * Use `create(C2B_MonsterDeathRequestSchema)` to create a new message.
 */
export const C2B_MonsterDeathRequestSchema = /*@__PURE__*/
  messageDesc(file_monster, 6);

/**
 * Describes the message Protocol.B2C_MonsterDeathNotification.
 * Use `create(B2C_MonsterDeathNotificationSchema)` to create a new message.
 */
export const B2C_MonsterDeathNotificationSchema = /*@__PURE__*/
  messageDesc(file_monster, 7);

