// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file room.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_client } from "./client_pb";
import { file_server } from "./server_pb";
import { file_struct } from "./struct_pb";

/**
 * Describes the file room.proto.
 */
export const file_room = /*@__PURE__*/
  fileDesc("Cgpyb29tLnByb3RvEghQcm90b2NvbCJFCg1DMkxfRW50ZXJSb29tEiQKBG1ldGEYASABKAsyFi5Qcm90b2NvbC5DMlNfTWV0YWRhdGESDgoGcm9vbUlkGAIgASgNIoABCg9MMkNfRW50ZXJSb29tTWUSJAoEbWV0YRgBIAEoCzIWLlByb3RvY29sLlMyQ19NZXRhZGF0YRIhCgV1c2VycxgCIAMoCzISLlByb3RvY29sLlVzZXJJbmZvEiQKCHJvb21JbmZvGAMgASgLMhIuUHJvdG9jb2wuUm9vbUluZm8iXwoSTDJDX0VudGVyUm9vbU90aGVyEiQKBG1ldGEYASABKAsyFi5Qcm90b2NvbC5TMkNfTWV0YWRhdGESIwoHbmV3VXNlchgCIAEoCzISLlByb3RvY29sLlVzZXJJbmZvIlUKDUMyTF9MZWF2ZVJvb20SJAoEbWV0YRgBIAEoCzIWLlByb3RvY29sLkMyU19NZXRhZGF0YRIOCgZyb29tSWQYAiABKA0SDgoGdXNlcklkGAMgASgJIjcKD0wyQ19MZWF2ZVJvb21NZRIkCgRtZXRhGAEgASgLMhYuUHJvdG9jb2wuUzJDX01ldGFkYXRhIkoKEkwyQ19MZWF2ZVJvb21PdGhlchIkCgRtZXRhGAEgASgLMhYuUHJvdG9jb2wuUzJDX01ldGFkYXRhEg4KBnVzZXJJZBgCIAEoCSI0CgxDMkxfUm9vbUxpc3QSJAoEbWV0YRgBIAEoCzIWLlByb3RvY29sLkMyU19NZXRhZGF0YSJXCgxMMkNfUm9vbUxpc3QSJAoEbWV0YRgBIAEoCzIWLlByb3RvY29sLlMyQ19NZXRhZGF0YRIhCgVyb29tcxgCIAMoCzISLlByb3RvY29sLlJvb21JbmZvIkUKDUMyTF9HYW1lU3RhcnQSJAoEbWV0YRgBIAEoCzIWLlByb3RvY29sLkMyU19NZXRhZGF0YRIOCgZyb29tSWQYAiABKA0iYQoNTDJDX0dhbWVTdGFydBIkCgRtZXRhGAEgASgLMhYuUHJvdG9jb2wuUzJDX01ldGFkYXRhEgwKBGhvc3QYAiABKAkSDAoEcG9ydBgDIAEoBRIOCgZyb29tSWQYBCABKA0iNAoOTDJCX0NyZWF0ZVJvb20SDgoGcm9vbUlkGAEgASgNEhIKCm1heFBsYXllcnMYAiABKA0iMwoOQjJMX0NyZWF0ZVJvb20SEQoJaXNDcmVhdGVkGAEgASgIEg4KBnJvb21JZBgCIAEoDWIGcHJvdG8z", [file_client, file_server, file_struct]);

/**
 * Describes the message Protocol.C2L_EnterRoom.
 * Use `create(C2L_EnterRoomSchema)` to create a new message.
 */
export const C2L_EnterRoomSchema = /*@__PURE__*/
  messageDesc(file_room, 0);

/**
 * Describes the message Protocol.L2C_EnterRoomMe.
 * Use `create(L2C_EnterRoomMeSchema)` to create a new message.
 */
export const L2C_EnterRoomMeSchema = /*@__PURE__*/
  messageDesc(file_room, 1);

/**
 * Describes the message Protocol.L2C_EnterRoomOther.
 * Use `create(L2C_EnterRoomOtherSchema)` to create a new message.
 */
export const L2C_EnterRoomOtherSchema = /*@__PURE__*/
  messageDesc(file_room, 2);

/**
 * Describes the message Protocol.C2L_LeaveRoom.
 * Use `create(C2L_LeaveRoomSchema)` to create a new message.
 */
export const C2L_LeaveRoomSchema = /*@__PURE__*/
  messageDesc(file_room, 3);

/**
 * Describes the message Protocol.L2C_LeaveRoomMe.
 * Use `create(L2C_LeaveRoomMeSchema)` to create a new message.
 */
export const L2C_LeaveRoomMeSchema = /*@__PURE__*/
  messageDesc(file_room, 4);

/**
 * Describes the message Protocol.L2C_LeaveRoomOther.
 * Use `create(L2C_LeaveRoomOtherSchema)` to create a new message.
 */
export const L2C_LeaveRoomOtherSchema = /*@__PURE__*/
  messageDesc(file_room, 5);

/**
 * Describes the message Protocol.C2L_RoomList.
 * Use `create(C2L_RoomListSchema)` to create a new message.
 */
export const C2L_RoomListSchema = /*@__PURE__*/
  messageDesc(file_room, 6);

/**
 * Describes the message Protocol.L2C_RoomList.
 * Use `create(L2C_RoomListSchema)` to create a new message.
 */
export const L2C_RoomListSchema = /*@__PURE__*/
  messageDesc(file_room, 7);

/**
 * Describes the message Protocol.C2L_GameStart.
 * Use `create(C2L_GameStartSchema)` to create a new message.
 */
export const C2L_GameStartSchema = /*@__PURE__*/
  messageDesc(file_room, 8);

/**
 * Describes the message Protocol.L2C_GameStart.
 * Use `create(L2C_GameStartSchema)` to create a new message.
 */
export const L2C_GameStartSchema = /*@__PURE__*/
  messageDesc(file_room, 9);

/**
 * Describes the message Protocol.L2B_CreateRoom.
 * Use `create(L2B_CreateRoomSchema)` to create a new message.
 */
export const L2B_CreateRoomSchema = /*@__PURE__*/
  messageDesc(file_room, 10);

/**
 * Describes the message Protocol.B2L_CreateRoom.
 * Use `create(B2L_CreateRoomSchema)` to create a new message.
 */
export const B2L_CreateRoomSchema = /*@__PURE__*/
  messageDesc(file_room, 11);

