// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file skill.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_enum } from "./enum_pb";

/**
 * Describes the file skill.proto.
 */
export const file_skill = /*@__PURE__*/
  fileDesc("Cgtza2lsbC5wcm90bxIIUHJvdG9jb2wiOAoQQzJCX1NraWxsUmVxdWVzdBIkCghjYXJkVHlwZRgBIAEoDjISLlByb3RvY29sLkNhcmRUeXBlIiYKEUMyQl9Ta2lsbFJlc3BvbnNlEhEKCWlzU3VjY2VzcxgBIAEoCCJHCg9DMkJfU2tpbGxOb3RpZnkSJAoIY2FyZFR5cGUYASABKA4yEi5Qcm90b2NvbC5DYXJkVHlwZRIOCgZ1c2VySWQYAiABKAViBnByb3RvMw", [file_enum]);

/**
 * Describes the message Protocol.C2B_SkillRequest.
 * Use `create(C2B_SkillRequestSchema)` to create a new message.
 */
export const C2B_SkillRequestSchema = /*@__PURE__*/
  messageDesc(file_skill, 0);

/**
 * Describes the message Protocol.C2B_SkillResponse.
 * Use `create(C2B_SkillResponseSchema)` to create a new message.
 */
export const C2B_SkillResponseSchema = /*@__PURE__*/
  messageDesc(file_skill, 1);

/**
 * Describes the message Protocol.C2B_SkillNotify.
 * Use `create(C2B_SkillNotifySchema)` to create a new message.
 */
export const C2B_SkillNotifySchema = /*@__PURE__*/
  messageDesc(file_skill, 2);

